# EXAMPLE CONFIG FILE

# Follow the instructions in the comments to adapt to your settings.

# References to Azure ML workspace (use cli args to override)
aml:
  "subscription_id": "4fcaeb12-537a-4364-9e34-0e499d30c4c1"
  "resource_group": "asa-fml"
  "workspace_name": "aml-fmldemo"

# Parameters to generate the degenerate FL graph
federated_learning:
  # orchestrator:
  #   # name of compute for orchestrator
  #   compute: "cpu-cluster-tp-orch"
  #   # name of datastore for orchestrator (saving model weights + aggregate)
  #   datastore: "datastore_tp_orch"

  silos: # silos are provided as a list, but in this basic example we have just one silo
    - compute: aml-cmp-arclocal # arclocal-ns # aml-cmp-arclocal # name of the attached Azure ML compute for the external silo - you will need to adjust this to match the one you created
      datastore: datastore_silo1_francecentral # name of the datastore for the external silo - you will need to adjust this to match the one you created
      # training inputs are specified below
      local_data_path: /mnt/localdata # the path at which the local data are accessed by the Azure Ml job.
      preprocessed_local_data: /mnt/localdata/output
    - compute: arclocal-ns # name of the attached Azure ML compute for the external silo - you will need to adjust this to match the one you created
      datastore: datastore_silo1_francecentral # name of the datastore for the external silo - you will need to adjust this to match the one you created
      # training inputs are specified below
      local_data_path: /mnt/localdata # the path at which the local data are accessed by the Azure Ml job.
      preprocessed_local_data: /mnt/localdata/output
